/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()

  useFrame(() => {
    group.current.rotation.y += 0.005

  })
  const { nodes, materials } = useGLTF('/Game-site.gltf')
  return (

    <group ref={group} {...props} dispose={null} scale={1.3} >
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh
        geometry={nodes['001__switchable'].geometry}
        material={materials['_switchable_b3600154-a42a-4398-9fc9-5b73a7ef3085']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['002_Keyboard'].geometry}
        material={materials['Keyboard_efa1d886-e8c1-472a-9eff-173f02237f96']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['003_Touch_Panel'].geometry}
        material={materials['Touch Bar_e4200440-1666-48ef-8696-494d75de3056']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['004_Body'].geometry}
        material={nodes['004_Body'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['005_Ports'].geometry}
        material={materials['Ports_8168536e-499e-4dfc-9344-d914f42148bf']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['006_Touchpad'].geometry}
        material={materials['Touchpad_988a87b3-691c-4020-a23b-e89383afdbb9']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['007_Screen_Back'].geometry}
        material={nodes['007_Screen_Back'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['008_Black_Inset'].geometry}
        material={materials['Display Rim_952dcad7-4c5e-4661-b83f-2ae513c7d15a']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['009_Rubber'].geometry}
        material={materials['Display Rubber_13f5a590-dafe-430e-a2c2-41269993af92']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>

  )
}

useGLTF.preload('/Game-site.gltf')
