/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
/* import { useFrame } from '@react-three/fiber' */

export default function Model(props) {
  const group = useRef()
  /* useFrame(() => {
    group.current.rotation.y += 0.005

  }) */

  const { nodes, materials } = useGLTF('/testrun3.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1, 0]}>
        <group position={[-113.98, 110.12, -7.1]}>
          <mesh
            geometry={nodes.Rectangle_2001.geometry}
            material={nodes.Rectangle_2001.material}
            position={[237.84, -18.36, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2002.geometry}
            material={nodes.Rectangle_2002.material}
            position={[10, -41.87, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2003.geometry}
            material={nodes.Rectangle_2003.material}
            position={[10, 5.32, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2004.geometry}
            material={nodes.Rectangle_2004.material}
            position={[10, 50.87, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group position={[0, 233.62, 9.14]}>
          <mesh
            geometry={nodes.Ellipse.geometry}
            material={materials['Material.002']}
            position={[-63.83, 1.75, 0.02]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-1, -1, -1]}
          />
          <mesh
            geometry={nodes.Ellipse001.geometry}
            material={materials['Material.003']}
            position={[63.83, 1.75, 0.02]}
          />
          <mesh
            geometry={nodes.Rectangle.geometry}
            material={nodes.Rectangle.material}
            position={[24.32, -0.8, 1.18]}
          />
          <mesh
            geometry={nodes.Rectangle_2.geometry}
            material={materials['Material.004']}
            position={[0, -0.75, -0.02]}
          />
          <mesh
            geometry={nodes.Rectangle001.geometry}
            material={nodes.Rectangle001.material}
            position={[-0.53, -0.8, 0.77]}
          />
        </group>
        <mesh
          geometry={nodes.antennas.geometry}
          material={materials['Material.005']}
          position={[120.62, -196.82, -5.52]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-1, -1, -1]}>
          <mesh
            geometry={nodes.Brackets001.geometry}
            material={materials['Material.006']}
            position={[0, 241.22, 1]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
          <mesh geometry={nodes.Brackets002.geometry} material={materials['Material.007']} position={[0, 0, -397.32]} />
          <mesh
            geometry={nodes.Brackets003.geometry}
            material={materials['Material.008']}
            position={[0, 241.22, -397.32]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-1, -1, -1]}
          />
        </mesh>
        <mesh
          geometry={nodes.Outer_sides.geometry}
          material={materials['iphone out color']}
          position={[0, 0, -15.56]}
        />
        <mesh geometry={nodes.Rectangle002.geometry} material={materials['Material.001']} position={[0, 0, -13.31]} />
        <mesh
          geometry={nodes.Screen.geometry}
          material={materials.screen}
          position={[0, 0, 7.96]}
          rotation={[-Math.PI, 0, 0]}
        />
      </group>
      <group position={[0, 0, 1000]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/testrun3.gltf')
